apiVersion: v1
kind: Service
metadata:
  name: go-web-file-svc # This name MUST match the Ingress backend
spec:
  type: ClusterIP      # Ensure this is NOT headless
  selector:
    app: go-web-file
  ports:
  - port: 80
    targetPort: 8080