apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer # Important for AWS
parameters:
  type: gp3
  fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-app-pvc # This name is the "ID" for the pod to find the disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-file-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-file
  template:
    metadata:
      labels:
        app: go-web-file
    spec:
      # Removed nodeSelector to allow Kubernetes to pick the best node
      securityContext:
        fsGroup: 65532
        runAsUser: 65532
        runAsNonRoot: true
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: app
        image: 880265510348.dkr.ecr.us-east-1.amazonaws.com/go-web-file:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DATA_PATH
          value: /app/data
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: go-app-pvc # MATCHES THE PVC NAME ABOVE